console.log("hi nithish")
setTimeout(()=>{
    console.log("hi man")
});
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")
console.log("hello man")