const os=require('os');
console.log(os.arch());
console.log(os.hostname());
console.log(os.tmpdir());
console.log(os.homedir());
console.log(os.release());
console.log(os.type());
console.log(os.version());
console.log(os.freemem());
console.log(os.totalmem());
console.log(os.endianness());
console.log(os.platform());